specfile_path: distro/cmake-extra-utils.spec

files_to_sync:
  - src: distro/cmake-extra-utils.spec
    dest: cmake-extra-utils.spec
  - .packit.yaml
  - src: distro/cmake-extra-utils.rpmlintrc
    dest: cmake-extra-utils.rpmlintrc
  - src: test/.fmf/
    dest: .fmf
  - src: test/plans/
    dest: plans
    filters:
      - "- test/plans/.gitignore"
      - "- test/plans/main.fmf.dist-git"
      - "- test/plans/rpmlint.fmf"
  - src: test/plans/main.fmf.dist-git
    dest: plans/main.fmf

upstream_package_name: CmakeExtraUtils
downstream_package_name: cmake-extra-utils
update_release: false
upstream_tag_template: v{version}
packit_instances: ["stg"]

jobs:
  - job: tests
    trigger: pull_request
    targets:
      - fedora-development
    fmf_path: ./test
    tf_extra_params:
      test:
        fmf:
          path: ./test
  - job: copr_build
    trigger: pull_request
    owner: lecris
    project: CMakeExtraUtils
    update_release: true
    release_suffix: "{PACKIT_RPMSPEC_RELEASE}"
    targets:
      - fedora-development
  - job: tests
    trigger: commit
    branch: main
    targets:
      - fedora-development
      - fedora-latest
    fmf_path: ./test
  - job: copr_build
    trigger: commit
    branch: main
    owner: lecris
    project: nightly
    targets:
      - fedora-development-x86_64
      - fedora-latest-x86_64
      - fedora-development-aarch64
      - fedora-latest-aarch64
    additional_repos:
      - copr://@scikit-build/release
  - job: copr_build
    trigger: release
    owner: lecris
    project: release
    targets:
      - fedora-development-x86_64
      - fedora-latest-x86_64
      - fedora-development-aarch64
      - fedora-latest-aarch64
    additional_repos:
      - copr://@scikit-build/release
## TODO: Disabled until released on src.fedoraproject.org
#  - job: propose_downstream
#    trigger: release
#    dist_git_branches:
#      - fedora-development
#  - job: koji_build
#    trigger: commit
#    dist_git_branches:
#      - fedora-development
#      - fedora-latest
#  - job: bodhi_update
#    trigger: commit
#    dist_git_branches:
#      - fedora-development
#      - fedora-latest
