specfile_path: .distro/cmake-extra-utils.spec

files_to_sync:
  - src: .distro/cmake-extra-utils.spec
    dest: cmake-extra-utils.spec
  - .packit.yaml
  - src: .distro/cmake-extra-utils.rpmlintrc
    dest: cmake-extra-utils.rpmlintrc
  # tmt setup
  - src: .distro/.fmf/
    dest: .fmf/
  - src: .distro/plans/
    dest: plans/
    filters:
      - "- test/plans/main.fmf.dist-git"
      - "- rpminspect.fmf"
      - "- rpmlint.fmf"
  - src: .distro/plans/main.fmf.dist-git
    dest: plans/main.fmf
  - src: .distro/tests/
    dest: tests/

upstream_package_name: CmakeExtraUtils
downstream_package_name: cmake-extra-utils
update_release: false
upstream_tag_template: v{version}

jobs:
  - job: tests
    trigger: pull_request
    targets:
      - fedora-all
      - epel-9
    fmf_path: .distro
  - job: copr_build
    trigger: pull_request
    owner: lecris
    project: CMakeExtraUtils
    update_release: true
    release_suffix: "{PACKIT_RPMSPEC_RELEASE}"
    targets:
      - fedora-all
      - epel-9
  - job: tests
    trigger: commit
    branch: main
    targets:
      - fedora-all
      - epel-9
    fmf_path: .distro
  - job: copr_build
    trigger: commit
    branch: main
    owner: lecris
    project: nightly
    targets:
      - fedora-all
      - epel-9
    additional_repos:
      - copr://@scikit-build/release
  - job: copr_build
    trigger: release
    owner: lecris
    project: release
    targets:
      - fedora-all
      - epel-9
    additional_repos:
      - copr://@scikit-build/release
## TODO: Disabled until released on src.fedoraproject.org
#  - job: propose_downstream
#    trigger: release
#    dist_git_branches:
#      - fedora-development
#  - job: koji_build
#    trigger: commit
#    dist_git_branches:
#      - fedora-development
#      - fedora-latest
#  - job: bodhi_update
#    trigger: commit
#    dist_git_branches:
#      - fedora-development
#      - fedora-latest
