repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
#  - repo: https://github.com/teemtee/tmt.git
#    rev: 1.21.0
#    hooks:
#      - id: tmt-lint
#        args: [ "--root","test" ]
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-tables
        exclude: doc\/(?!README\.md).*
    # TODO: Temporarily separate docs formatiing
    # https://github.com/executablebooks/mdformat/issues/234
    # TODO: Disabled due to lack of colon-fence support
  #  - repo: https://github.com/executablebooks/mdformat
  #    rev: 0.7.16
  #    hooks:
  #      - id: mdformat
  #        additional_dependencies:
  #          - mdformat-myst
  #        files: doc\/(?!README).*\.md$
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.21.0
    hooks:
      - id: check-github-workflows
      - id: check-readthedocs
