name: release
run-name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to release
        required: true

jobs:
  # TODO: tests and docs are not aligned when called from workflow_dispatch :/
  pre-commit:
    uses: ./.github/workflows/step_pre-commit.yaml
  tests:
    needs: [ pre-commit ]
    uses: ./.github/workflows/step_test.yaml
    permissions:
      contents: read
      checks: write
      pull-requests: write
  docs:
    needs: [ pre-commit ]
    uses: ./.github/workflows/step_docs.yaml

  release:
    needs: [ tests, docs ]
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
      - uses: softprops/action-gh-release@v2
        with:
          name: CMakeExtraUtils ${{ github.ref_name }}
          draft: true
          prerelease: ${{ contains(github.ref, 'rc') }}
          generate_release_notes: true
