name: release
run-name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"
  workflow_dispatch:

jobs:
  pre-commit:
    uses: ./.github/workflows/step_pre-commit.yaml
  tests:
    needs: [ pre-commit ]
    uses: ./.github/workflows/step_test.yaml
  docs:
    needs: [ pre-commit ]
    uses: ./.github/workflows/step_docs.yaml

  release:
    needs: [ tests, docs ]
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: softprops/action-gh-release@v1
        with:
          name: CMakeExtraUtils ${{ github.ref_name }}
          draft: true
          prerelease: ${{ contains(github.ref, 'rc') }}
          generate_release_notes: true
