name: test
run-name: Run tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  tests:
    name: CMake ${{ matrix.cmake }}
    runs-on: ubuntu-latest
    container: ghcr.io/lecrisut/dev-env:main
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      fail-fast: false
      matrix:
        cmake: ["3.20", "latest", "latestrc"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Note: Proper solution is: https://github.com/actions/runner/issues/2033#issuecomment-1598547465
      - name: Temporary fix for git permissions
        run: |
          git config --global --add safe.directory "*"
          git config --global user.email "bot@github.com"
          git config --global user.name "GitHub Actions Bot"
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      # TODO: This will be migrated to standalone actions
      - name: Setup tmt environment
        run: dnf install -y tmt tmt+report-junit
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: ${{ matrix.cmake }}
      - name: Build and test native CMake
        run: |
          # Not running presets because of minimum CMake version being tested
          cmake -B ./build
          ctest --test-dir ./build --output-on-failure
          echo "CMakeExtraUtils_ROOT=$(pwd)/build" >> $GITHUB_ENV
      # TODO: This will be migrated to standalone actions
      - name: Run tmt tests
        run: >
          tmt --root ./test run --all provision -h local report -h junit --file report.xml
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: JUnit-CMake-${{ matrix.cmake }}
          path: report.xml
  report:
    name: Report JUnit
    needs: [ tests ]
    permissions:
      contents: read
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download test results
        uses: actions/download-artifact@v4
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        with:
          check_name: CMake Tests (mikepenz)
          detailed_summary: true
          annotate_notice: true
          include_passed: true
          report_paths: "*/report.xml"
      - name: Test Report
        uses: dorny/test-reporter@v1
        with:
          name: CMake Tests (dorny)
          path: "*/report.xml"
          reporter: java-junit
          fail-on-error: false
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          check_name: CMake Tests (EnricoMi)
          files: "*/report.xml"
    if: always()
