name: test
run-name: Run tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  tests:
    name: CMake ${{ matrix.cmake }}
    runs-on: ubuntu-latest
    container: ghcr.io/lecrisut/dev-env:main
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      fail-fast: false
      matrix:
        cmake: ["3.20", "latest", "latestrc"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Note: Proper solution is: https://github.com/actions/runner/issues/2033#issuecomment-1598547465
      - name: Temporary fix for git permissions
        run: |
          git config --global --add safe.directory "*"
          git config --global user.email "bot@github.com"
          git config --global user.name "GitHub Actions Bot"
      - name: Setup tmt
        uses: LecrisUT/tmt-actions/setup-tmt@v1
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: ${{ matrix.cmake }}
      - name: Build and test native CMake
        run: |
          # Not running presets because of minimum CMake version being tested
          cmake -B ./build
          ctest --test-dir ./build --output-on-failure
          echo "CMakeExtraUtils_ROOT=$(pwd)/build" >> $GITHUB_ENV
      # TODO: This will be migrated to standalone actions
      - name: Run tmt tests
        uses: LecrisUT/tmt-actions/run-tmt@v1
        with:
          root: test
          report-artifact: JUnit-CMake-${{ matrix.cmake }}
  report:
    name: Report JUnit
    needs: [ tests ]
    permissions:
      contents: read
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Download test results
        uses: actions/download-artifact@v4
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "*/report.xml"
          large_files: true
          report_individual_runs: true
          report_suite_logs: any
    if: always()
